baseurl = "/"
Paginate = 5

[params]
  env = "production"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "My blog"
weight = 1

[Languages.pt]
title = "Meu blog"
weight = 2

# datocms:start
#title = "Creative Inc."
#languageCode = "en"
# datocms:end